module: StrasbourgParkAPI
author: Yannick Heinrich
author_url: https://github.com/yageek/
github_url: https://github.com/yageek/StrasbourgParkAPI
copyright: '© 2020 [Yannick Heinrich](https://github.com/yageek) under [open source license](https://github.com/yageek/siesta/blob/StrasbourgParkAPI/LICENSE).'
